#server.port=9100
server.servlet.context-path=/example
server.servlet.session.timeout=1m
server.tomcat.mbeanregistry.enabled=true

management.endpoints.web.exposure.include=health,info,metrics

example.application.name=@project.name@
example.application.description=@project.description@
example.application.version=@project.version@
example.application.rest-api.package=io.github.quinnandrews.scheduler.modules

example.data.application.schema=scheduling
example.data.application.user=scheduling
example.data.migration.user=scheduling_flyway

example.shedlock.table.name=${example.data.application.schema}.shedlock

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${example.data.application.user}
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=3

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${example.data.application.schema}

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

#hibernate:
#generate_statistics: true
#format_sql: true
#jdbc:
#lob.non_contextual_creation: true
#batch_size: 100
#fetch_size: 100
#batch_versioned_data: true

spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory
spring.jpa.properties.hibernate.cache.use_minimal_puts=true

spring.flyway.user=${example.data.migration.user}
spring.flyway.baseline-on-migrate=true
spring.flyway.schemas=${example.data.application.schema}
spring.flyway.table=schema_version
spring.flyway.locations=classpath:data/migration
spring.flyway.placeholder-replacement=true
spring.flyway.placeholders.application-schema=${example.data.application.schema}
spring.flyway.placeholders.application-user=${example.data.application.user}
spring.flyway.placeholders.migration-user=${example.data.migration.user}

javers.sqlSchema=${example.data.application.schema}
javers.sqlSchemaManagementEnabled=false

# Enables default use of @JsonView, which treats un-annotated fields as included in all Views.
# Used primarily in Response Objects to conditionally include or exclude various properties.
# See https://reflectoring.io/jackson-jsonview-tutorial/
spring.jackson.mapper.default-view-inclusion=true

# Exception handling and logging are deferred to Listener implementations.
# In some cases there is no need to log the Exception, like ConstraintViolationExceptions
# thrown during validation checks, for example.
logging.level.org.jeasy.rules.core.DefaultRulesEngine=OFF
