<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.quinnandrews</groupId>
        <artifactId>scheduler</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>docs</artifactId>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>default-jar</id>
                        <phase>none</phase>
                    </execution>
                </executions>
                <!--
                Configured in this manner so that no jar is built
                for this module, since its code is not intended for
                distribution.
                -->
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
                <!--
                Configured in this manner so that no jar is built
                for this module, since its code is not intended for
                distribution.
                -->
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>default-resources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>resources</goal>
                        </goals>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testResources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>resources</goal>
                        </goals>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>com.coderplus.maven.plugins</groupId>-->
<!--                <artifactId>copy-rename-maven-plugin</artifactId>-->
<!--                <version>1.0.1</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>copy-readme-files</id>-->
<!--                        <phase>generate-sources</phase>-->
<!--                        <goals>-->
<!--                            <goal>copy</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <fileSets>-->
<!--                                <fileSet>-->
<!--                                    <sourceFile>../README.md</sourceFile>-->
<!--                                    <destinationFile>${basedir}/docs/readmes/project-readme.md</destinationFile>-->
<!--                                </fileSet>-->
<!--                                <fileSet>-->
<!--                                    <sourceFile>README.md</sourceFile>-->
<!--                                    <destinationFile>${basedir}/docs/readmes/docs-readme.md</destinationFile>-->
<!--                                </fileSet>-->
<!--                                <fileSet>-->
<!--                                    <sourceFile>../service/README.md</sourceFile>-->
<!--                                    <destinationFile>${basedir}/docs/readmes/service-readme.md</destinationFile>-->
<!--                                </fileSet>-->
<!--                            </fileSets>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>docusaurus-build</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <executable>yarn</executable>
                            <arguments>
                                <argument>build</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>